language: scala
scala:
  - 2.10.4
  - 2.11.7
env:
  - SPARK_VER=1.5.2
  - SPARK_VER=1.4.1
  - SPARK_VER=1.6.0
  # - SPARK_VER=1.3.1 (failing at the moment)
script:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M" sbt -Dspark.version=$SPARK_VER -Dscala.version=$TRAVIS_SCALA_VERSION ++$TRAVIS_SCALA_VERSION test
